### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by QLjast** [msk86/ygo-card-print#1]
ygo-card-print不是很会用，npm install总是失败，求教一下谢谢

**Comment by notbucai** [comment]
这边没问题，怀疑你是网络问题。
可考虑使用taobao代理安装

npm install --registry https://registry.npm.taobao.org

**Comment by msk86** [comment]
也可以考虑使用[cnpm](https://www.npmjs.com/package/cnpm)

**Comment by southern-dust** [comment]
使用 node v14.18.1 和安装 python2 之后成功

**Comment by southern-dust** [comment]
默认去编译确实出现问题，废了一番功夫之后终于成了。
使用 ``node v14.18.1``，
在 ``package.json`` 中更改 ``ygo-card`` 依赖为 ``^1.2.7``，删掉 ``package-lock.json``，执行 ``npm audit fix``，然后执行 ``npm install`` 应该就可以使用了

**Comment by southern-dust** [comment]
> 默认去编译确实出现问题，废了一番功夫之后终于成了。 使用 `node v14.18.1`， 在 `package.json` 中更改 `ygo-card` 依赖为 `^1.2.7`，删掉 `package-lock.json`，执行 `npm audit fix`，然后执行 `npm install` 应该就可以使用了

我收回原来的话，切换到 ``node v12.22.7`` 后使用 ``yarn`` 就好了
