### ISSUE TITLE
怎么把繁体改为日文？

### ISSUE THREAD

**Issue by XiaoQiSAMA** [msk86/ygo-card-print#2]
我不是太懂js，简单试了一下在index.js中的new Card的.map中加入config属性，并改defaultconfig为defaultJpConfig的文件地址，但是报了Cannot read property 'moldSize' of undefined的error，求解决

**Comment by msk86** [comment]
Hi there,

I have updated the code so it can support multilingual, you can pass an extra optional bash parameter `lang` when you run `node index.js ydk lang`.
The supported languages are: `cn`, `jp`, `en`.
But where you really need to do is: find a `Japanese cards.cdb` and rename it to `cards-jp.cdb`, then move it to `/resources` folder.

BTW, I've also send a PR to the `yugioh-card` repo to fix some multilingual issue. Once they publish the new version of npm package, I will update my package.json accordingly, so you might still need to wait for 1-2 days.
Thanks.

Hi 兄弟/姐妹，
我把代码改了一下，现在代码可以支持多语言了。你可以在执行`node index.js ydk`的时候加一个额外的可选参数`lang`，执行：`node index.js ydk lang`。
现在可以支持的语言有：`cn`，`jp`，`en`。
但是需要你自己做的事情是，你要去找一个`日文版的cards.cdb`，重命名为`cards-jp.cdb`，并把这个文件放在`/resources`目录下。我这边找不到最新版的。
另外， 我给`yugioh-card`那边也发了个PR，修了一些那边多语言支持的问题。等他发布了新版本的npm包，我这边也会更新依赖的版本，所以你可能还需要等1-2天。

谢谢。

**Comment by XiaoQiSAMA** [comment]
谢谢解答😊

**Comment by msk86** [comment]
> 谢谢解答😊

All good now, you can pull the code and install the new packages. :) Then I will close this issue.
