### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by kps333** [msk86/ygo-card-print#3]
花了三天时间查网络和更改设置，最后还是败给BUG了
最开始是找不到module'ygo-card',在文件夹内移入这个模组后显示找不到卡片数据库，进入程序锁死中文后显示没有getmultidata这三个函数，最后换用了2021年11月的ygo-card模组后直接就报语法错误，然后就没有然后了

**Comment by msk86** [comment]
能详细说说吗？例如提供一下你执行的命令和对应的截图？从npm install开始？

**Comment by kps333** [comment]
作者您好！
&nbsp; &nbsp; &nbsp; 现在我已经解决了这个问题了。我后来查看了一下package.json文件后发现问题是在于现在在npm上的ygo-card模组已经是1.3.6版本了，而且在我的本地js环境中不能使用‘./’的方式略去路径。而软件需求的版本是1.3.2的ygo-card模组。但是在1.3.6版本中ygo-card模组已经没有getMultiData、renderPDF和CardNode这三个函数或模块了，这样看来我当时的操作就显得很可笑了。




当时的操作是这样的（现在已经修好了就不打算再弄坏之后复刻错误了，就简单口述一下）：
第一步node ./(此处略去路径名）index.js tq(我想玩天气卡组) cn
提示no such module 'ygo-card'
第二步 npm install -g ygo-card,再次运行 node ./index.js tq cn
仍然提示no such module 'ygo-card'
第三步复制ygo-card文件到软件路径中，再次运行
提示'card database no exist'
这一步开始要修改index.js文件，打开index.js,修改程序如图



再次运行，显示‘getMultiData’不是一个函数


这时候从github上获取2021年12月31日版本的ygo-card模组并用其中的index.js替换掉2022年2月版本的模组的index.js，再次运行
这个时候出现语法错误（可能是这个时候定义的类型仍然不对，但是刚学三天js知识的我意识到按这条路走不可能走得通了，所以系统地学了一下js应用的结构，发现package.json可能有我想要的信息）


最后npm install ***@***.***,在路径新建output文件夹之后程序就顺利跑起来了。


此外这里还有一个小问题。

这一行程序中原先的error都不能被识别并抛出，这样打印1105之后的卡都会出现死机的问题，需要把error改为‘error’


总而言之非常感谢作者制作了这样方便的软件，祝您学习、工作顺利，每天愉快！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "msk86/ygo-card-print"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月2日(星期六) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [msk86/ygo-card-print] 运行错误 (Issue #3)





 
能详细说说吗？例如提供一下你执行的命令和对应的截图？从npm install开始？

**Comment by msk86** [comment]
> 此外这里还有一个小问题。 这一行程序中原先的error都不能被识别并抛出，这样打印1105之后的卡都会出现死机的问题，需要把error改为‘error’ 

确实，ygo-card升级了，我这边还没有时间改代码，必须用1.3.2才行。
请问一下`这一行程序`是指哪一行呢？能把你会死机的卡组发给我吗？我调一下。另外如果需要更新卡图请联系我。

**Comment by kps333** [comment]
这个卡组里这里面因为包含了1108更新的两张新卡“月天气 彩虹”和“天气预报”运行到js第33行的时候就会因为抛不出“error”出错





即&nbsp;out.on('error', () =&gt; {console.log(`fail to create ${file}`, 'error');reject('error');});这一行代码


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "msk86/ygo-card-print"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 下午3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [msk86/ygo-card-print] 运行错误 (Issue #3)





  
此外这里还有一个小问题。 这一行程序中原先的error都不能被识别并抛出，这样打印1105之后的卡都会出现死机的问题，需要把error改为‘error’
  
确实，ygo-card升级了，我这边还没有时间改代码，必须用1.3.2才行。
 请问一下这一行程序是指哪一行呢？能把你会死机的卡组发给我吗？我调一下。另外如果需要更新卡图请联系我。

**Comment by msk86** [comment]
error的问题我修复了，少传了一个参数。。。

1108的新卡，也不应该会走到error那里呀……cdb是用的代码库里的cdb吗？还是你自己换了cdb？
另外能把这两张卡的id发给我不？

**Comment by kps333** [comment]
天气预报是18720257
月天气 彩虹是95515518




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "msk86/ygo-card-print"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 下午4:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [msk86/ygo-card-print] 运行错误 (Issue #3)





 
error的问题我修复了，少传了一个参数。。。
 
1108的新卡，也不应该会走到error那里呀……cdb是用的代码库里的cdb吗？还是你自己换了cdb？
 另外能把这两张卡的id发给我不？

**Comment by msk86** [comment]
无法重现
